language: node_js
node_js: 12.18.3
cache:
  directories:
    - node_modules
install:
  - yarn install
script: -yarn build
deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
  skip-cleanup: true
  local_dir: build
  on:
    branch: main
