name: deploy_to_firebase

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy_to_firebase_hosting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Install Dependency
        run: yarn
      - name: Run Build
        CI: false
        run: yarn build

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
